// let products = [
//     {
//         id: 1,
//         title: 'Santa Claus Stocking ',
//         category: 'Stockings', 
//         description: 'Traditional Christmas sock with funny applications. The sock is made of felt with a knitted top.',
//         price: 15.00,
//         imageUrl: '../img_project/Santa_Claus_Stocking.png',
//         quantity:4,
//     },
//     {
//         id: 2,
//         title: 'Christmas Red Stocking',
//         category: 'Stockings', 
//         description: 'Classic Christmas stocking in red and white, nothing extra. The stocking is made of textile, decorated with pompons, and is ready to be filled with sweets.',
//         price: 22.00,
//         imageUrl: '../img_project/Christmas_Red_Stocking.png',
//         quantity:4,
//     },
//     {
//         id: 3,
//         title: 'Stocking With Pompons',
//         category: 'Stockings', 
//         description: 'Knitted Christmas stocking in traditional colors. The top of the stocking is decorated with red and green pompons.',
//         price: 22.00,
//         imageUrl: '../img_project/Stocking_With_Pompons.png',
//         quantity:6,
//     },
//     {
//         id: 4,
//         title: 'Stocking With Balls ',
//         category: 'Stockings', 
//         description: 'Red and green stocking with colorful Christmas balls. Fill it with candles or small presents!',
//         price: 18.00,
//         imageUrl: '../img_project/Stocking_With_Balls.png',
//         quantity:11,
//     },
//     {
//         id: 5,
//         title: 'Red Christmas Balls ',
//         category: 'Christmas Balls', 
//         description: 'A great set of 40 baubles of different colors and diameters. Actually, you get everything you need to decorate your X-mas tree in one box. By the way, the box is excellent for further storage of the balls after Christmas.',
//         price: 22.00,
//         imageUrl: '../img_project/Red_Christmas_Balls.png',
//         quantity:8,
//     },
//     {
//         id: 6,
//         title: 'Gold Christmas Balls ',
//         category: 'Christmas Balls', 
//         description: 'Set of 30 gold baubles made of glass and plastic. There are shiny and matt balls in this set with a diameter of 6-10 cm. The set comes in a nice storage box that you can use even after Christmas.',
//         price: 10.00,
//         imageUrl: '../img_project/Gold_Christmas_Balls.png',
//         quantity:10,
//     },
//     {
//         id: 7,
//         title: 'Citrus Wreath ',
//         category: 'Wreath', 
//         description: 'Add some spice to your Christmas! This wreath features pine branches mixed in with brown pinecones, cotton flowers, red beads, and bright dried orange slices!',
//         price: 89.00,
//         imageUrl: '../img_project/Citrus_Wreath.png',
//         quantity:2,
//     },

// ];